library/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
app_name="books"
urlpatterns = [
   path('',views.home,name="home"),
   path('add',views.add_books,name="add"),
   path('view',views.view_books,name="view"),
   path('search',views.search,name="search"),
   path('detail/<int:p>',views.detail,name="detail"),
   path('edit/<int:m>',views.edit,name="edit"),
   path('delete/<int:i>',views.delete,name="delete"),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('users/',include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views
app_name="users"
urlpatterns = [
    path('reg',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
    path('users',views.viewusers,name="users"),
]

library/books/models.py
from django.db import models


# Create your models here.

#Attributes ........table definition.
class Book(models.Model):
    title = models.CharField(max_length=20)
    author = models.CharField(max_length=20)
    pages = models.IntegerField()
    price = models.IntegerField()
    language = models.CharField(max_length=20)
    cover=models.ImageField(upload_to="images")
    pdf=models.FileField(upload_to="pdf")


    def __str__(self):
        return self.title

library/users/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    place=models.CharField(max_length=20)
    gender=models.CharField(max_length=10)
    email=models.CharField(max_length=20)

    def __str__(self):
        return self.name

library/books/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


from books.models import Book
# Create your views here.
def home(request):
    context={'name':'Arun','age':27}
    return render(request,'home.html',context)
@login_required
def add_books(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        pa=request.POST['pa']
        l=request.POST['l']

        c=request.FILES['i']
        f=request.FILES['f']

        b=Book.objects.create(title=t,author=a,price=p,pages=pa,language=l,cover=c,pdf=f)
        b.save()
        return view_books(request)
    return render(request,'add.html')
@login_required()
def view_books(request):
    # k=con.execute('select * from Book')  reads all records from table Book and assigns it to k
    k=Book.objects.all()
    return render(request,'view.html',{'book':k})
@login_required()
def detail(request,p):
    k=Book.objects.get(id=p)
    return render(request,'detail.html',{'book':k})
@login_required()
def edit(request,m):
    k = Book.objects.get(id=m)
    if (request.method == "POST"):
        k.title=request.POST['t']
        k.author=request.POST['a']
        k.price=request.POST['p']
        k.pages=request.POST['pa']
        k.language=request.POST['l']
        if(request.FILES.get('i')==None):
            k.save()
        else:
            k.cover=request.FILES['i']

        if(request.FILES.get('f')==None):
            k.save()
        else:
            k.pdf=request.FILES['f']

        k.save()

        return view_books(request)

    return render(request,'edit.html',{'book':k})

@login_required()
def delete(request,i):
    k=Book.objects.get(id=i)
    k.delete()
    return view_books(request)

from django.db.models import Q
def search(request):
    k=None
    if(request.method=="POST"):
        query=request.POST['q']
        if query:
            k=Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))

    return render(request,'search.html',{'book':k})

library/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required


from django.http import HttpResponse
from users.models import Users
# Create your views here.
def register(request):
    if(request.method=='POST'):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        f=request.POST['f']
        l=request.POST['l']
        e=request.POST['e']
        if(p==cp):
           print("hello")
           u=User.objects.create_user(username=u,password=p,first_name=f,last_name=l,email=e)
           u.save()
        else:
             return HttpResponse("passwords are not same")
        return redirect('users:login')

    return render(request,'register.html')
def user_login(request):
    if (request.method == "POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('books:home')
        else:
            return HttpResponse("invalid")
    return render(request, 'login.html')
@login_required()
def user_logout(request):
    logout(request)
    return redirect('users:login')
@login_required
def viewusers(request):
    k=Users.objects.all()
    context={'user':k}
    return render(request,'viewusers.html',context)

library/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2>Add Books Here</h2>
<form method="POST" enctype="multipart/form-data">

{% csrf_token %}

<div class="mb-3">
  <label  class="form-label">Title</label>
  <input type="text" class="form-control" name="t" placeholder="Enter the Title">
</div>

  <div class="mb-3">
  <label  class="form-label">Author</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the Author">
</div>

  <div class="mb-3">
  <label  class="form-label">Price</label>
  <input type="number" class="form-control"  name="p" placeholder="Enter the Price">
</div>

  <div class="mb-3">
  <label  class="form-label">Pages</label>
  <input type="number" class="form-control"  name="pa" placeholder="Enter the Pages">
</div>

  <div class="mb-3">
  <label  class="form-label">Language</label>
  <input type="text" class="form-control" name="l" placeholder="Enter the Language">
</div>

    <div class="mb-3">
  <label  class="form-label">Cover</label>
  <input type="file" class="form-control" name="i">
</div>

    <div class="mb-3">
  <label  class="form-label">Pdf</label>
  <input type="file" class="form-control" name="f">
</div>

  <div class="mb-3">
  <input type="submit" value="ADD">
</div>

</form>
{% endblock %}

library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">LibraryApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:add' %}">Add Books</a>
        </li>
            <li class="nav-item">
          <a class="nav-link" href="{% url 'books:view' %}">View Books</a>
        </li>

          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
        </li>
        {% else %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
            <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
        {% endif %}
      </ul>
      <form method="POST" class="d-flex ms-5" action="{% url 'books:search' %}">
        {% csrf_token %}

        <input class="form-control me-2" type="search"  name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}





</body>
</html>

library/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
<h2>Book Details</h2>
<div class="card  mx-auto mb-3 bg-success" style="max-width:800px;">
  <div class="row g-0">
    <div class="col-md-4 ">
      <img src="{{book.cover.url}}" class="p-3" height="300px" width="100%" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{book.title}}</h5>
        <p class="card-text">{{book.author}}</p>
          <p class="card-text">{{book.pages}}</p>
          <p class="card-text">{{book.price}}</p>
        <p class="card-text"><small class="text-muted">{{book.language}}</small></p>
        <a href="{{book.pdf.url}}" class="btn btn-danger">Download</a>
      </div>
    </div>
  </div>
</div>
    </div>
{% endblock %}

library/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center">Edit Books Here</h2>
<form method="POST" enctype="multipart/form-data">

{% csrf_token %}

<div class="mb-3">
  <label  class="form-label">Title</label>
  <input type="text" class="form-control" name="t" value="{{book.title}}" placeholder="Enter the Title">
</div>

  <div class="mb-3">
  <label  class="form-label">Author</label>
  <input type="text" class="form-control" name="a" value="{{book.author}}" placeholder="Enter the Author">
</div>

  <div class="mb-3">
  <label  class="form-label">Price</label>
  <input type="number" class="form-control"  name="p" value="{{book.price}}" placeholder="Enter the Price">
</div>

  <div class="mb-3">
  <label  class="form-label">Pages</label>
  <input type="number" class="form-control"  name="pa"  value="{{book.pages}}" placeholder="Enter the Pages">
</div>

  <div class="mb-3">
  <label  class="form-label">Language</label>
  <input type="text" class="form-control" name="l" value="{{book.language}}" placeholder="Enter the Language">
</div>

    <div class="mb-3">
  <label  class="form-label">Cover</label>
        <img src="{{book.cover.url}}">
  <input type="file" class="form-control" name="i">
</div>

    <div class="mb-3">
  <label  class="form-label">Pdf</label>
        <a href="{{book.pdf.url}}">pdf</a>
  <input type="file" class="form-control" name="f">
</div>

  <div class="mb-3">
  <input type="submit" value="ADD">
</div>

</form>
{% endblock %}

library/templates/home.html
{% extends 'base.html' %}
{% load static %}
<!--<a href="{% url 'books:home' %}">Home</a>-->
<!--<a href="{% url 'books:add' %}">Add Books</a>-->
<!--<a href="{% url 'books:view' %}">View Books</a>-->
<!--<a href="{% url 'users:register' %}">Register</a>-->
<!--<a href="{% url 'users:login' %}">Login</a>-->
<!--<a href="{% url 'users:logout' %}">Logout</a>-->
{% block content %}
<h2 class="text-center text-info mt-3">Welcome to library Application<span>
{% if user.is_authenticated %}
{{user.username}}
{% else %}
 Guest</span></h2>
{% endif %}
{% endblock %}

library/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Welcome To Login Page</h2>
<form method="POST">

{% csrf_token %}

<div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>

    <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the Password">
</div>
      <div class="mb-3">
  <input type="submit" value="submit">
</div>
</form>
{% endblock %}

library/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Register page</h2>
<form method="POST">

{% csrf_token %}

<div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>

    <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the Password">
</div>

        <div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter the Confirm Password">
</div>

    <div class="mb-3">
  <label  class="form-label">Firstname</label>
  <input type="text" class="form-control" name="f" placeholder="Enter the firstname">
</div>

    <div class="mb-3">
  <label  class="form-label">Lastname</label>
  <input type="text" class="form-control" name="l" placeholder="Enter the lastname">
</div>

    <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter the email">
</div>
  <div class="mb-3">
  <input type="submit" value="submit">
</div>

</form>
{% endblock %}

library/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Search Books</h2>
<table class="table table bordered bg-light">
    <tr>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PAGES</th>
        <th>PRICE</th>
        <th>LANGUAGE</th>
        <th>DOCUMENT</th>

    </tr>
    {% for i in book %}
    <tr>
        <td><img src="{{i.cover.url}}"></td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.pages}}</td>
        <td>{{i.price}}</td>
        <td>{{i.language}}</td>
        <td><a href="{{i.pdf.url}}">Download</a></td>


    </tr>
    {% endfor %}
</table>
{% endblock %}

library/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>View Books</h2>
<table class="table table bordered bg-light">
    <tr>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PAGES</th>
        <th>PRICE</th>
        <th>LANGUAGE</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>

    </tr>
    {% for i in book %}
    <tr>
        <td><img src="{{i.cover.url}}"></td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.pages}}</td>
        <td>{{i.price}}</td>
        <td>{{i.language}}</td>
        <td><a href="{{i.pdf.url}}">Download</a></td>
        <td><a href="{% url 'books:detail' i.id %}" class="btn btn-danger">view</a></td>
        <td><a href="{% url 'books:edit' i.id %}" class="btn btn-danger">edit</a></td>
        <td><a href="{% url 'books:delete' i.id %}" class="btn btn-danger">delete</a></td>
    </tr>
    {% endfor %}
</table>
<!--<ol>-->
<!--    {% for i in book %}-->
<!--    <li>-->
<!--    <ul>-->
<!--        <li>Title: {{i.title}}</li>-->
<!--        <li>Author: {{i.author}}</li>-->
<!--        <li>Pages: {{i.pages}}}</li>-->
<!--        <li>Price: {{i.price}}</li>-->
<!--        <li>Language: {{i.language}}</li>-->
<!--    </ul>-->
<!--    </li>-->
<!--    {% endfor %}-->
<!--</ol>-->
{% endblock %}

library/templates/viewusers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>View Users</h2>
<ol>
    {% for i in user %}
    <li>
    <ul>
        <li>Name: {{i.name}}</li>
        <li>Age: {{i.age}}</li>
        <li>Place: {{i.place}}}</li>
        <li>Gender: {{i.gender}}</li>
        <li>Email: {{i.email}}</li>
    </ul>
    </li>
    {% endfor %}
</ol>
{% endblock %}